swagger: '2.0'

info:
  version: 1.0.0
  title: Fillex API
  description: ''

servers:
  - url: http://localhost:3000
    description: 'Server locale'

host: 'localhost:3000'

basePath: /api/fillex

consumes:
  - application/json
produces:
  - application/json

tags:
- name: 'Ban'
  description: 'Fornisce l''elenco dei ban'
- name: 'Champion'
  description: 'Mostra aaaa'
- name: 'Match'
  description: 'Descrizione'
- name: 'Profile'
  description: 'Descrizione'
- name: 'User'
  description: 'Descrizione'
- name: 'Warning'
  description: 'Descrizione'

definitions:

  banModel:
    type: object
    title: Ban
    properties:
      idban:
        type: integer
      iduser:
        type: integer
      idchampion:
        type: number
      idmatch:
        type: number
      isactive:
        type: number
      date:
        type: string
    required:
      - iduser
      - idchampion
      - idmatch

  championModel:
    type: object
    title: Champion
    properties:
      name:
        type: string
        example: no_stress
    required:
      - name

  matchModel:
    type: object
    title: Match
    properties:
      name:
        type: string
        example: no_stress
    required:
      - name

  profileModel:
    type: object
    title: Profile
    properties:
      name:
        type: string
        example: no_stress
    required:
      - name
            
  userModel:
    type: object
    title: User
    properties:
      name:
        type: string
        example: no_stress
    required:
      - name

  warningModel:
    type: object
    title: Warning
    properties:
      name:
        type: string
        example: no_stress
    required:
      - name

paths:

  /bans:
    get:
      tags:
        - Ban
      description: Fornisce tutti i ban
      responses:
        '200':
          description: OK
        '400':
          description: Bad request
        '401':
          description: Authorization information is missing or invalid
        '404':
          description: A user with the specified ID was not found
        '5XX':
          description: Unexpected error
    post:
      tags:
        - Ban
      description: Crea un nuovo ban
      parameters:
        - name: body
          in: body
          description: an example
          required: true
          schema: 
            $ref: "#/definitions/banModel"         
      responses:
        '200':
          description: Ok
        '400':
          description: Bad request
        '401':
          description: Authorization information is missing or invalid
        '404':
          description: A user with the specified ID was not found
        '5XX':
          description: Unexpected server error

  /champions:
    get:
      tags:
        - Champion
      description: Fetch all examples
      responses:
        200:
          description: Returns all examples

  /matches:
    get:
      tags:
        - Match
      description: Fetch all examples
      responses:
        200:
          description: Returns all examples

  /profiles:
    get:
      tags:
        - Profile
      description: Fetch all examples
      responses:
        200:
          description: Returns all examples

  /users:
    get:
      tags:
        - User
      description: Fetch all examples
      responses:
        200:
          description: Returns all examples

  /warnings:
    get:
      tags:
        - Warning
      description: Fetch all examples
      responses:
        200:
          description: Returns all examples

  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification